# This is a basic workflow to help you get started with Actions

name: armtemplatedeployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
      branches:
        - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armdeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
            creds: ${{ secrets.azure_credentials }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 0716d370-926c-485b-a73a-34512d202445
          region: EastUS2
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="EastUS2"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        #id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 0716d370-926c-485b-a73a-34512d202445
          region: EastUS2
          template: ./arm-templates/storageaccount.json
          parameters:
            ./arm-templates/storageaccount.parameters.json
            storageAccountName=saargus002
            location="EastUS"
          deploymentMode: incremental

      #- run: echo ${{ steps.storageAccountDelpoy.outputs.BlobUri }}
