# This is a basic workflow to help you get started with Actions

name: armtemplatedeployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
      branches:
        - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armdeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
            creds: ${{ secrets.azure_credentials }}

      - name: Deploy Resource Group rg-githubactions with AZ CLI
        uses: Azure/cli@1.0.4
        with: 
          inlinescript: | 
            az deployment sub create --location "EastUS2" --template-file ./arm-templates/resourcegroup.json
